namespace D846031
{
partial class F846031
{
private System.ComponentModel.IContainer components = null;
protected override void Dispose(bool disposing)
{
if (disposing && (components != null))
{
components.Dispose();
}
base.Dispose(disposing);
}
private void InitializeComponent()
{
this.Size = new System.Drawing.Size(750,218);
this.MaximumSize = new System.Drawing.Size(750,218);
this.Text ="RDLTest";
this.r84603_Location_rectangle1 = new System.Windows.Forms.Panel();
this.r84603_Location_rectangle3 = new System.Windows.Forms.Panel();
this.r84603_Location_Vmg_Location = new System.Windows.Forms.Label();
this.r84603_Location_Vmg_Location.AccessibleName = "r84603_Location_Vmg_Location";
this.r84603_Location_rectangle2 = new System.Windows.Forms.Panel();
this.r84603_Location_rectangle6 = new System.Windows.Forms.Panel();
this.r84603_Location_rectangle17 = new System.Windows.Forms.Panel();
this.r84603_Location_Txtm_LocationDescription = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Location_Lbl_LocationNotes = new System.Windows.Forms.Label();
this.r84603_Location_rectangle16 = new System.Windows.Forms.Panel();
this.r84603_Location_Cmb_E_W_StreetID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Location_Lbl_E_W_Street = new System.Windows.Forms.Label();
this.r84603_Location_rectangle15 = new System.Windows.Forms.Panel();
this.r84603_Location_Cmb_N_S_StreetID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Location_Lbl_N_S_Street = new System.Windows.Forms.Label();
this.r84603_Location_rectangle5 = new System.Windows.Forms.Panel();
this.r84603_Location_rectangle14 = new System.Windows.Forms.Panel();
this.r84603_Location_Txt_DistrictProject = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Location_Lbl_DistrictProject = new System.Windows.Forms.Label();
this.r84603_Location_rectangle13 = new System.Windows.Forms.Panel();
this.r84603_Location_Cmb_GridID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Location_Lbl_Grid = new System.Windows.Forms.Label();
this.r84603_Location_rectangle12 = new System.Windows.Forms.Panel();
this.r84603_Location_Cmb_OperationalAreaID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Location_Lbl_OperationalArea = new System.Windows.Forms.Label();
this.r84603_Location_rectangle11 = new System.Windows.Forms.Panel();
this.r84603_Location_Cmb_AdministrativeAreaID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Location_Lbl_AdminArea = new System.Windows.Forms.Label();
this.r84603_Location_rectangle4 = new System.Windows.Forms.Panel();
this.r84603_Location_rectangle10 = new System.Windows.Forms.Panel();
this.r84603_Location_Txt_YCoordinate = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Location_Lbl_YCoordinate = new System.Windows.Forms.Label();
this.r84603_Location_rectangle9 = new System.Windows.Forms.Panel();
this.r84603_Location_Txt_XCoordinate = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Location_Lbl_XCoordinate = new System.Windows.Forms.Label();
this.r84603_Location_rectangle8 = new System.Windows.Forms.Panel();
this.r84603_Location_Cmb_GPSByID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Location_Lbl_GPSBy = new System.Windows.Forms.Label();
this.r84603_Location_rectangle7 = new System.Windows.Forms.Panel();
this.r84603_Location_Txt_GPSDate = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Location_Lbl_GPSDate = new System.Windows.Forms.Label();
this.r84603_Location_rectangle1.Location = new System.Drawing.Point(0,0);
this.r84603_Location_rectangle3.Location = new System.Drawing.Point(706,0);
this.r84603_Location_rectangle2.Location = new System.Drawing.Point(0,0);
this.r84603_Location_rectangle6.Location = new System.Drawing.Point(0,104);
this.r84603_Location_rectangle17.Location = new System.Drawing.Point(193,0);
this.r84603_Location_rectangle16.Location = new System.Drawing.Point(0,52);
this.r84603_Location_rectangle15.Location = new System.Drawing.Point(0,0);
this.r84603_Location_rectangle5.Location = new System.Drawing.Point(0,52);
this.r84603_Location_rectangle14.Location = new System.Drawing.Point(536,0);
this.r84603_Location_rectangle13.Location = new System.Drawing.Point(424,0);
this.r84603_Location_rectangle12.Location = new System.Drawing.Point(193,0);
this.r84603_Location_rectangle11.Location = new System.Drawing.Point(0,0);
this.r84603_Location_rectangle4.Location = new System.Drawing.Point(0,0);
this.r84603_Location_rectangle10.Location = new System.Drawing.Point(543,0);
this.r84603_Location_rectangle9.Location = new System.Drawing.Point(387,0);
this.r84603_Location_rectangle8.Location = new System.Drawing.Point(150,0);
this.r84603_Location_rectangle7.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Vmg_Location.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Txtm_LocationDescription.Location = new System.Drawing.Point(6,25);
this.r84603_Location_Txtm_LocationDescription.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_LocationNotes.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Cmb_E_W_StreetID.Location = new System.Drawing.Point(9,25);
this.r84603_Location_Cmb_E_W_StreetID.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_E_W_Street.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Cmb_N_S_StreetID.Location = new System.Drawing.Point(9,25);
this.r84603_Location_Cmb_N_S_StreetID.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_N_S_Street.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Txt_DistrictProject.Location = new System.Drawing.Point(7,25);
this.r84603_Location_Txt_DistrictProject.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_DistrictProject.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Cmb_GridID.Location = new System.Drawing.Point(6,25);
this.r84603_Location_Cmb_GridID.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_Grid.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Cmb_OperationalAreaID.Location = new System.Drawing.Point(18,25);
this.r84603_Location_Cmb_OperationalAreaID.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_OperationalArea.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Cmb_AdministrativeAreaID.Location = new System.Drawing.Point(12,25);
this.r84603_Location_Cmb_AdministrativeAreaID.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_AdminArea.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Txt_YCoordinate.Location = new System.Drawing.Point(18,25);
this.r84603_Location_Txt_YCoordinate.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_YCoordinate.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Txt_XCoordinate.Location = new System.Drawing.Point(12,25);
this.r84603_Location_Txt_XCoordinate.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_XCoordinate.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Cmb_GPSByID.Location = new System.Drawing.Point(12,25);
this.r84603_Location_Cmb_GPSByID.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_GPSBy.Location = new System.Drawing.Point(0,0);
this.r84603_Location_Txt_GPSDate.Location = new System.Drawing.Point(25,25);
this.r84603_Location_Txt_GPSDate.BackColor = System.Drawing.Color.White; 
this.r84603_Location_Lbl_GPSDate.Location = new System.Drawing.Point(0,0);
this.r84603_Location_rectangle1.Size = new System.Drawing.Size(750,210);
this.r84603_Location_rectangle3.Size = new System.Drawing.Size(44,208);
this.r84603_Location_rectangle2.Size = new System.Drawing.Size(712,210);
this.r84603_Location_rectangle6.Size = new System.Drawing.Size(706,104);
this.r84603_Location_rectangle17.Size = new System.Drawing.Size(513,103);
this.r84603_Location_rectangle16.Size = new System.Drawing.Size(193,51);
this.r84603_Location_rectangle15.Size = new System.Drawing.Size(193,52);
this.r84603_Location_rectangle5.Size = new System.Drawing.Size(712,52);
this.r84603_Location_rectangle14.Size = new System.Drawing.Size(170,52);
this.r84603_Location_rectangle13.Size = new System.Drawing.Size(112,52);
this.r84603_Location_rectangle12.Size = new System.Drawing.Size(231,52);
this.r84603_Location_rectangle11.Size = new System.Drawing.Size(193,52);
this.r84603_Location_rectangle4.Size = new System.Drawing.Size(706,52);
this.r84603_Location_rectangle10.Size = new System.Drawing.Size(163,52);
this.r84603_Location_rectangle9.Size = new System.Drawing.Size(156,52);
this.r84603_Location_rectangle8.Size = new System.Drawing.Size(237,52);
this.r84603_Location_rectangle7.Size = new System.Drawing.Size(150,52);
this.r84603_Location_Vmg_Location.Size = new System.Drawing.Size(44,208);
this.r84603_Location_Txtm_LocationDescription.Size = new System.Drawing.Size(500,75);
this.r84603_Location_Lbl_LocationNotes.Size = new System.Drawing.Size(131,18);
this.r84603_Location_Cmb_E_W_StreetID.Size = new System.Drawing.Size(175,18);
this.r84603_Location_Lbl_E_W_Street.Size = new System.Drawing.Size(131,18);
this.r84603_Location_Cmb_N_S_StreetID.Size = new System.Drawing.Size(175,18);
this.r84603_Location_Lbl_N_S_Street.Size = new System.Drawing.Size(128,18);
this.r84603_Location_Txt_DistrictProject.Size = new System.Drawing.Size(156,18);
this.r84603_Location_Lbl_DistrictProject.Size = new System.Drawing.Size(131,18);
this.r84603_Location_Cmb_GridID.Size = new System.Drawing.Size(100,18);
this.r84603_Location_Lbl_Grid.Size = new System.Drawing.Size(100,18);
this.r84603_Location_Cmb_OperationalAreaID.Size = new System.Drawing.Size(206,18);
this.r84603_Location_Lbl_OperationalArea.Size = new System.Drawing.Size(150,18);
this.r84603_Location_Cmb_AdministrativeAreaID.Size = new System.Drawing.Size(175,18);
this.r84603_Location_Lbl_AdminArea.Size = new System.Drawing.Size(150,18);
this.r84603_Location_Txt_YCoordinate.Size = new System.Drawing.Size(137,18);
this.r84603_Location_Lbl_YCoordinate.Size = new System.Drawing.Size(100,18);
this.r84603_Location_Txt_XCoordinate.Size = new System.Drawing.Size(137,18);
this.r84603_Location_Lbl_XCoordinate.Size = new System.Drawing.Size(100,18);
this.r84603_Location_Cmb_GPSByID.Size = new System.Drawing.Size(218,18);
this.r84603_Location_Lbl_GPSBy.Size = new System.Drawing.Size(100,18);
this.r84603_Location_Txt_GPSDate.Size = new System.Drawing.Size(118,18);
this.r84603_Location_Lbl_GPSDate.Size = new System.Drawing.Size(106,18);
this.r84603_Location_Vmg_Location.Text ="Location";
this.r84603_Location_Txtm_LocationDescription.Tag ="LocationDescription";
this.r84603_Location_Txtm_LocationDescription.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Txtm_LocationDescription.Multiline = true;
this.r84603_Location_Txtm_LocationDescription.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
this.r84603_Location_Lbl_LocationNotes.Text ="Location Notes:";
this.r84603_Location_Cmb_E_W_StreetID.Tag ="E_W_StreetID";
this.r84603_Location_Cmb_E_W_StreetID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_E_W_Street.Text ="East/West Street:";
this.r84603_Location_Cmb_N_S_StreetID.Tag ="N_S_StreetID";
this.r84603_Location_Cmb_N_S_StreetID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_N_S_Street.Text ="North/South Street:";
this.r84603_Location_Txt_DistrictProject.Tag ="District_Project";
this.r84603_Location_Txt_DistrictProject.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_DistrictProject.Text ="District / Project:";
this.r84603_Location_Cmb_GridID.Tag ="GridID";
this.r84603_Location_Cmb_GridID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_Grid.Text ="Grid:";
this.r84603_Location_Cmb_OperationalAreaID.Tag ="OperationalAreaID";
this.r84603_Location_Cmb_OperationalAreaID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_OperationalArea.Text ="Operational Area:";
this.r84603_Location_Cmb_AdministrativeAreaID.Tag ="AdministrativeAreaID";
this.r84603_Location_Cmb_AdministrativeAreaID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_AdminArea.Text ="Administrative Area:";
this.r84603_Location_Txt_YCoordinate.Tag ="Y_Coord";
this.r84603_Location_Txt_YCoordinate.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_YCoordinate.Text ="Y Coordinate:";
this.r84603_Location_Txt_XCoordinate.Tag ="X_Coord";
this.r84603_Location_Txt_XCoordinate.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_XCoordinate.Text ="X Coordinate:";
this.r84603_Location_Cmb_GPSByID.Tag ="GPSByID";
this.r84603_Location_Cmb_GPSByID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_GPSBy.Text ="GPS By:";
this.r84603_Location_Txt_GPSDate.Tag ="GPSDate";
this.r84603_Location_Txt_GPSDate.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Location_Lbl_GPSDate.Text ="GPS Date:";
this.r84603_Location_Vmg_Location.BackColor = System.Drawing.Color.Silver;
this.r84603_Location_Lbl_LocationNotes.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_E_W_Street.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_N_S_Street.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_DistrictProject.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_Grid.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_OperationalArea.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_AdminArea.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_YCoordinate.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_XCoordinate.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_GPSBy.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_Lbl_GPSDate.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Location_rectangle1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Location_rectangle2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Location_rectangle17.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Location_rectangle16.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Location_rectangle15.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Location_rectangle13.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Location_rectangle12.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Location_rectangle2.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Location_rectangle17.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Location_rectangle16.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Location_rectangle15.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Location_rectangle13.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Location_rectangle12.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Location_Vmg_Location.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
this.r84603_Location_Lbl_LocationNotes.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_E_W_Street.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_N_S_Street.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_DistrictProject.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_Grid.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_OperationalArea.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_AdminArea.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_YCoordinate.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_XCoordinate.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_GPSBy.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Lbl_GPSDate.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Location_Txtm_LocationDescription.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
this.r84603_Location_Txt_DistrictProject.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
this.r84603_Location_Txt_YCoordinate.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Location_Txt_XCoordinate.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Location_Txt_GPSDate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
this.r84603_Location_Vmg_Location.Font = new System.Drawing.Font("Arial",12f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Txtm_LocationDescription.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_LocationNotes.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Cmb_E_W_StreetID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_E_W_Street.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Cmb_N_S_StreetID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_N_S_Street.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Txt_DistrictProject.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_DistrictProject.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Cmb_GridID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_Grid.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Cmb_OperationalAreaID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_OperationalArea.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Cmb_AdministrativeAreaID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_AdminArea.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Txt_YCoordinate.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_YCoordinate.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Txt_XCoordinate.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_XCoordinate.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Cmb_GPSByID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_GPSBy.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Txt_GPSDate.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Lbl_GPSDate.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Location_Vmg_Location.Padding  = new System.Windows.Forms.Padding( 2,2,2,2);
this.r84603_Location_Txtm_LocationDescription.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_LocationNotes.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Cmb_E_W_StreetID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_E_W_Street.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Cmb_N_S_StreetID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_N_S_Street.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Txt_DistrictProject.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_DistrictProject.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Cmb_GridID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_Grid.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Cmb_OperationalAreaID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_OperationalArea.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Cmb_AdministrativeAreaID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_AdminArea.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Txt_YCoordinate.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_YCoordinate.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Txt_XCoordinate.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_XCoordinate.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Cmb_GPSByID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Location_Lbl_GPSBy.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_Txt_GPSDate.Padding  = new System.Windows.Forms.Padding( 2,0,1,1);
this.r84603_Location_Lbl_GPSDate.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Location_rectangle3.Controls.Add(this.r84603_Location_Vmg_Location);
this.r84603_Location_rectangle1.Controls.Add(this.r84603_Location_rectangle3);
this.r84603_Location_rectangle17.Controls.Add(this.r84603_Location_Txtm_LocationDescription);
this.r84603_Location_rectangle17.Controls.Add(this.r84603_Location_Lbl_LocationNotes);
this.r84603_Location_rectangle6.Controls.Add(this.r84603_Location_rectangle17);
this.r84603_Location_rectangle16.Controls.Add(this.r84603_Location_Cmb_E_W_StreetID);
this.r84603_Location_rectangle16.Controls.Add(this.r84603_Location_Lbl_E_W_Street);
this.r84603_Location_rectangle6.Controls.Add(this.r84603_Location_rectangle16);
this.r84603_Location_rectangle15.Controls.Add(this.r84603_Location_Cmb_N_S_StreetID);
this.r84603_Location_rectangle15.Controls.Add(this.r84603_Location_Lbl_N_S_Street);
this.r84603_Location_rectangle6.Controls.Add(this.r84603_Location_rectangle15);
this.r84603_Location_rectangle2.Controls.Add(this.r84603_Location_rectangle6);
this.r84603_Location_rectangle14.Controls.Add(this.r84603_Location_Txt_DistrictProject);
this.r84603_Location_rectangle14.Controls.Add(this.r84603_Location_Lbl_DistrictProject);
this.r84603_Location_rectangle5.Controls.Add(this.r84603_Location_rectangle14);
this.r84603_Location_rectangle13.Controls.Add(this.r84603_Location_Cmb_GridID);
this.r84603_Location_rectangle13.Controls.Add(this.r84603_Location_Lbl_Grid);
this.r84603_Location_rectangle5.Controls.Add(this.r84603_Location_rectangle13);
this.r84603_Location_rectangle12.Controls.Add(this.r84603_Location_Cmb_OperationalAreaID);
this.r84603_Location_rectangle12.Controls.Add(this.r84603_Location_Lbl_OperationalArea);
this.r84603_Location_rectangle5.Controls.Add(this.r84603_Location_rectangle12);
this.r84603_Location_rectangle11.Controls.Add(this.r84603_Location_Cmb_AdministrativeAreaID);
this.r84603_Location_rectangle11.Controls.Add(this.r84603_Location_Lbl_AdminArea);
this.r84603_Location_rectangle5.Controls.Add(this.r84603_Location_rectangle11);
this.r84603_Location_rectangle2.Controls.Add(this.r84603_Location_rectangle5);
this.r84603_Location_rectangle10.Controls.Add(this.r84603_Location_Txt_YCoordinate);
this.r84603_Location_rectangle10.Controls.Add(this.r84603_Location_Lbl_YCoordinate);
this.r84603_Location_rectangle4.Controls.Add(this.r84603_Location_rectangle10);
this.r84603_Location_rectangle9.Controls.Add(this.r84603_Location_Txt_XCoordinate);
this.r84603_Location_rectangle9.Controls.Add(this.r84603_Location_Lbl_XCoordinate);
this.r84603_Location_rectangle4.Controls.Add(this.r84603_Location_rectangle9);
this.r84603_Location_rectangle8.Controls.Add(this.r84603_Location_Cmb_GPSByID);
this.r84603_Location_rectangle8.Controls.Add(this.r84603_Location_Lbl_GPSBy);
this.r84603_Location_rectangle4.Controls.Add(this.r84603_Location_rectangle8);
this.r84603_Location_rectangle7.Controls.Add(this.r84603_Location_Txt_GPSDate);
this.r84603_Location_rectangle7.Controls.Add(this.r84603_Location_Lbl_GPSDate);
this.r84603_Location_rectangle4.Controls.Add(this.r84603_Location_rectangle7);
this.r84603_Location_rectangle2.Controls.Add(this.r84603_Location_rectangle4);
this.r84603_Location_rectangle1.Controls.Add(this.r84603_Location_rectangle2);
this.Controls.Add(this.r84603_Location_rectangle1);
//this.operationSmartPartWorkSpace = new Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace();
//this.operationSmartPartWorkSpace.Location = new System.Drawing.Point(50,30);
//this.operationSmartPartWorkSpace.Name ="operationSmartPartWorkSpace";
//this.operationSmartPartWorkSpace.Size = new System.Drawing.Size(421, 45);
//this.operationSmartPartWorkSpace.TabIndex = 120;
//this.operationSmartPartWorkSpace.Text ="OperationSmartPart";
//this.Controls.Add(this.operationSmartPartWorkSpace);
this.Resize += new System.EventHandler(this.BaseSmartPart_Resize);
this.Load += new System.EventHandler(this.F846031_Load);
}

System.Windows.Forms.Label r84603_Location_Lbl_GPSDate;
TerraScan.UI.Controls.TerraScanTextBox r84603_Location_Txt_GPSDate;
System.Windows.Forms.Panel r84603_Location_rectangle7;
System.Windows.Forms.Label r84603_Location_Lbl_GPSBy;
TerraScan.UI.Controls.TerraScanComboBox r84603_Location_Cmb_GPSByID;
System.Windows.Forms.Panel r84603_Location_rectangle8;
System.Windows.Forms.Label r84603_Location_Lbl_XCoordinate;
TerraScan.UI.Controls.TerraScanTextBox r84603_Location_Txt_XCoordinate;
System.Windows.Forms.Panel r84603_Location_rectangle9;
System.Windows.Forms.Label r84603_Location_Lbl_YCoordinate;
TerraScan.UI.Controls.TerraScanTextBox r84603_Location_Txt_YCoordinate;
System.Windows.Forms.Panel r84603_Location_rectangle10;
System.Windows.Forms.Panel r84603_Location_rectangle4;
System.Windows.Forms.Label r84603_Location_Lbl_AdminArea;
TerraScan.UI.Controls.TerraScanComboBox r84603_Location_Cmb_AdministrativeAreaID;
System.Windows.Forms.Panel r84603_Location_rectangle11;
System.Windows.Forms.Label r84603_Location_Lbl_OperationalArea;
TerraScan.UI.Controls.TerraScanComboBox r84603_Location_Cmb_OperationalAreaID;
System.Windows.Forms.Panel r84603_Location_rectangle12;
System.Windows.Forms.Label r84603_Location_Lbl_Grid;
TerraScan.UI.Controls.TerraScanComboBox r84603_Location_Cmb_GridID;
System.Windows.Forms.Panel r84603_Location_rectangle13;
System.Windows.Forms.Label r84603_Location_Lbl_DistrictProject;
TerraScan.UI.Controls.TerraScanTextBox r84603_Location_Txt_DistrictProject;
System.Windows.Forms.Panel r84603_Location_rectangle14;
System.Windows.Forms.Panel r84603_Location_rectangle5;
System.Windows.Forms.Label r84603_Location_Lbl_N_S_Street;
TerraScan.UI.Controls.TerraScanComboBox r84603_Location_Cmb_N_S_StreetID;
System.Windows.Forms.Panel r84603_Location_rectangle15;
System.Windows.Forms.Label r84603_Location_Lbl_E_W_Street;
TerraScan.UI.Controls.TerraScanComboBox r84603_Location_Cmb_E_W_StreetID;
System.Windows.Forms.Panel r84603_Location_rectangle16;
System.Windows.Forms.Label r84603_Location_Lbl_LocationNotes;
TerraScan.UI.Controls.TerraScanTextBox r84603_Location_Txtm_LocationDescription;
System.Windows.Forms.Panel r84603_Location_rectangle17;
System.Windows.Forms.Panel r84603_Location_rectangle6;
System.Windows.Forms.Panel r84603_Location_rectangle2;
System.Windows.Forms.Label r84603_Location_Vmg_Location;
System.Windows.Forms.Panel r84603_Location_rectangle3;
System.Windows.Forms.Panel r84603_Location_rectangle1;
private Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace operationSmartPartWorkSpace;
}
}











