namespace D846032
{
partial class F846032
{
private System.ComponentModel.IContainer components = null;
protected override void Dispose(bool disposing)
{
if (disposing && (components != null))
{
components.Dispose();
}
base.Dispose(disposing);
}
private void InitializeComponent()
{
this.Size = new System.Drawing.Size(756,268);
this.MaximumSize = new System.Drawing.Size(756,268);
this.Text ="RDLTest";
this.r84603_Properties_rectangle1 = new System.Windows.Forms.Panel();
this.r84603_Properties_rectangle3 = new System.Windows.Forms.Panel();
this.r84603_Properties_Vmg_Properties = new System.Windows.Forms.Label();
this.r84603_Properties_Vmg_Properties.AccessibleName = "r84603_Properties_Vmg_Properties";
this.r84603_Properties_rectangle2 = new System.Windows.Forms.Panel();
this.r84603_Properties_rectangle7 = new System.Windows.Forms.Panel();
this.r84603_Properties_rectangle26 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_SurfaceCover = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_SurfaceCoverID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle27 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_Comment = new System.Windows.Forms.Label();
this.r84603_Properties_Txtm_Comment = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle25 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_AccessType = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_AccessTypeID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle6 = new System.Windows.Forms.Panel();
this.r84603_Properties_rectangle19 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_Depth = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_Depth = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle23 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_EastFlowLine = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_EastFlowLine = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle22 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_SouthFlowLine = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_SouthFlowLine = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle21 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_NorthFlowLine = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_NorthFlowLine = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle20 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_FlowElevation = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_FlowElevation = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle24 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_WestFlowLine = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_WestFlowLine = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle5 = new System.Windows.Forms.Panel();
this.r84603_Properties_rectangle18 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_Diameter = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_Diameter = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle17 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_RingMaterial = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_RingMaterialID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle16 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_JunctionMaterial = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_JunctionMaterialID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle15 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_FrameType = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_FrameTypeID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle14 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_JunctionType = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_JunctionTypeID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle4 = new System.Windows.Forms.Panel();
this.r84603_Properties_rectangle8 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_JunctionID = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_JunctionID = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle10 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_Enabled = new System.Windows.Forms.Label();
this.r84603_Properties_Chk_IsEnabled = new TerraScan.UI.Controls.TerraScanCheckBox();
this.r84603_Properties_rectangle9 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_CID = new System.Windows.Forms.Label();
this.r84603_Properties_Txt_CID = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84603_Properties_rectangle11 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_LifeCycleStatus = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_LifeCycleStatusID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle12 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_CoverDiameter = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_CoverDiameterID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle13 = new System.Windows.Forms.Panel();
this.r84603_Properties_Lbl_CoverType = new System.Windows.Forms.Label();
this.r84603_Properties_Cmb_CoverTYpeID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84603_Properties_rectangle1.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_rectangle3.Location = new System.Drawing.Point(706,0);
this.r84603_Properties_rectangle2.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_rectangle7.Location = new System.Drawing.Point(0,156);
this.r84603_Properties_rectangle26.Location = new System.Drawing.Point(0,52);
this.r84603_Properties_rectangle27.Location = new System.Drawing.Point(181,0);
this.r84603_Properties_rectangle25.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_rectangle6.Location = new System.Drawing.Point(0,104);
this.r84603_Properties_rectangle19.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_rectangle23.Location = new System.Drawing.Point(461,0);
this.r84603_Properties_rectangle22.Location = new System.Drawing.Point(336,0);
this.r84603_Properties_rectangle21.Location = new System.Drawing.Point(218,0);
this.r84603_Properties_rectangle20.Location = new System.Drawing.Point(125,0);
this.r84603_Properties_rectangle24.Location = new System.Drawing.Point(586,0);
this.r84603_Properties_rectangle5.Location = new System.Drawing.Point(0,52);
this.r84603_Properties_rectangle18.Location = new System.Drawing.Point(630,0);
this.r84603_Properties_rectangle17.Location = new System.Drawing.Point(455,0);
this.r84603_Properties_rectangle16.Location = new System.Drawing.Point(299,0);
this.r84603_Properties_rectangle15.Location = new System.Drawing.Point(137,0);
this.r84603_Properties_rectangle14.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_rectangle4.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_rectangle8.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_rectangle10.Location = new System.Drawing.Point(205,0);
this.r84603_Properties_rectangle9.Location = new System.Drawing.Point(87,0);
this.r84603_Properties_rectangle11.Location = new System.Drawing.Point(261,0);
this.r84603_Properties_rectangle12.Location = new System.Drawing.Point(398,0);
this.r84603_Properties_rectangle13.Location = new System.Drawing.Point(535,0);
this.r84603_Properties_Vmg_Properties.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Lbl_SurfaceCover.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Cmb_SurfaceCoverID.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Cmb_SurfaceCoverID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_Comment.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txtm_Comment.Location = new System.Drawing.Point(12,25);
this.r84603_Properties_Txtm_Comment.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_AccessType.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Cmb_AccessTypeID.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Cmb_AccessTypeID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_Depth.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txt_Depth.Location = new System.Drawing.Point(12,26);
this.r84603_Properties_Txt_Depth.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_EastFlowLine.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txt_EastFlowLine.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Txt_EastFlowLine.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_SouthFlowLine.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txt_SouthFlowLine.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Txt_SouthFlowLine.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_NorthFlowLine.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txt_NorthFlowLine.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Txt_NorthFlowLine.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_FlowElevation.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txt_FlowElevation.Location = new System.Drawing.Point(6,26);
this.r84603_Properties_Txt_FlowElevation.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_WestFlowLine.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txt_WestFlowLine.Location = new System.Drawing.Point(6,26);
this.r84603_Properties_Txt_WestFlowLine.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_Diameter.Location = new System.Drawing.Point(1,0);
this.r84603_Properties_Txt_Diameter.Location = new System.Drawing.Point(6,26);
this.r84603_Properties_Txt_Diameter.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_RingMaterial.Location = new System.Drawing.Point(1,1);
this.r84603_Properties_Cmb_RingMaterialID.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Cmb_RingMaterialID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_JunctionMaterial.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Cmb_JunctionMaterialID.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Cmb_JunctionMaterialID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_FrameType.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Cmb_FrameTypeID.Location = new System.Drawing.Point(6,26);
this.r84603_Properties_Cmb_FrameTypeID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_JunctionType.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Cmb_JunctionTypeID.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Cmb_JunctionTypeID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_JunctionID.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txt_JunctionID.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Txt_JunctionID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_Enabled.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Chk_IsEnabled.Location = new System.Drawing.Point(18,26);
this.r84603_Properties_Chk_IsEnabled.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_CID.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Txt_CID.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Txt_CID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_LifeCycleStatus.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Cmb_LifeCycleStatusID.Location = new System.Drawing.Point(15,26);
this.r84603_Properties_Cmb_LifeCycleStatusID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_CoverDiameter.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Cmb_CoverDiameterID.Location = new System.Drawing.Point(6,26);
this.r84603_Properties_Cmb_CoverDiameterID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_Lbl_CoverType.Location = new System.Drawing.Point(0,0);
this.r84603_Properties_Cmb_CoverTYpeID.Location = new System.Drawing.Point(6,26);
this.r84603_Properties_Cmb_CoverTYpeID.BackColor = System.Drawing.Color.White; 
this.r84603_Properties_rectangle1.Size = new System.Drawing.Size(750,262);
this.r84603_Properties_rectangle3.Size = new System.Drawing.Size(44,260);
this.r84603_Properties_rectangle2.Size = new System.Drawing.Size(706,262);
this.r84603_Properties_rectangle7.Size = new System.Drawing.Size(706,105);
this.r84603_Properties_rectangle26.Size = new System.Drawing.Size(181,51);
this.r84603_Properties_rectangle27.Size = new System.Drawing.Size(525,103);
this.r84603_Properties_rectangle25.Size = new System.Drawing.Size(181,52);
this.r84603_Properties_rectangle6.Size = new System.Drawing.Size(706,52);
this.r84603_Properties_rectangle19.Size = new System.Drawing.Size(125,52);
this.r84603_Properties_rectangle23.Size = new System.Drawing.Size(125,52);
this.r84603_Properties_rectangle22.Size = new System.Drawing.Size(125,52);
this.r84603_Properties_rectangle21.Size = new System.Drawing.Size(118,52);
this.r84603_Properties_rectangle20.Size = new System.Drawing.Size(93,52);
this.r84603_Properties_rectangle24.Size = new System.Drawing.Size(120,52);
this.r84603_Properties_rectangle5.Size = new System.Drawing.Size(706,52);
this.r84603_Properties_rectangle18.Size = new System.Drawing.Size(76,52);
this.r84603_Properties_rectangle17.Size = new System.Drawing.Size(175,52);
this.r84603_Properties_rectangle16.Size = new System.Drawing.Size(156,52);
this.r84603_Properties_rectangle15.Size = new System.Drawing.Size(162,52);
this.r84603_Properties_rectangle14.Size = new System.Drawing.Size(137,52);
this.r84603_Properties_rectangle4.Size = new System.Drawing.Size(706,52);
this.r84603_Properties_rectangle8.Size = new System.Drawing.Size(87,52);
this.r84603_Properties_rectangle10.Size = new System.Drawing.Size(56,52);
this.r84603_Properties_rectangle9.Size = new System.Drawing.Size(118,52);
this.r84603_Properties_rectangle11.Size = new System.Drawing.Size(137,52);
this.r84603_Properties_rectangle12.Size = new System.Drawing.Size(137,52);
this.r84603_Properties_rectangle13.Size = new System.Drawing.Size(171,52);
this.r84603_Properties_Vmg_Properties.Size = new System.Drawing.Size(44,260);
this.r84603_Properties_Lbl_SurfaceCover.Size = new System.Drawing.Size(131,18);
this.r84603_Properties_Cmb_SurfaceCoverID.Size = new System.Drawing.Size(162,18);
this.r84603_Properties_Lbl_Comment.Size = new System.Drawing.Size(131,18);
this.r84603_Properties_Txtm_Comment.Size = new System.Drawing.Size(506,68);
this.r84603_Properties_Lbl_AccessType.Size = new System.Drawing.Size(131,18);
this.r84603_Properties_Cmb_AccessTypeID.Size = new System.Drawing.Size(162,18);
this.r84603_Properties_Lbl_Depth.Size = new System.Drawing.Size(125,18);
this.r84603_Properties_Txt_Depth.Size = new System.Drawing.Size(93,18);
this.r84603_Properties_Lbl_EastFlowLine.Size = new System.Drawing.Size(100,18);
this.r84603_Properties_Txt_EastFlowLine.Size = new System.Drawing.Size(106,18);
this.r84603_Properties_Lbl_SouthFlowLine.Size = new System.Drawing.Size(112,18);
this.r84603_Properties_Txt_SouthFlowLine.Size = new System.Drawing.Size(106,18);
this.r84603_Properties_Lbl_NorthFlowLine.Size = new System.Drawing.Size(106,18);
this.r84603_Properties_Txt_NorthFlowLine.Size = new System.Drawing.Size(96,18);
this.r84603_Properties_Lbl_FlowElevation.Size = new System.Drawing.Size(93,18);
this.r84603_Properties_Txt_FlowElevation.Size = new System.Drawing.Size(81,18);
this.r84603_Properties_Lbl_WestFlowLine.Size = new System.Drawing.Size(100,18);
this.r84603_Properties_Txt_WestFlowLine.Size = new System.Drawing.Size(106,18);
this.r84603_Properties_Lbl_Diameter.Size = new System.Drawing.Size(62,18);
this.r84603_Properties_Txt_Diameter.Size = new System.Drawing.Size(62,18);
this.r84603_Properties_Lbl_RingMaterial.Size = new System.Drawing.Size(100,18);
this.r84603_Properties_Cmb_RingMaterialID.Size = new System.Drawing.Size(156,18);
this.r84603_Properties_Lbl_JunctionMaterial.Size = new System.Drawing.Size(118,18);
this.r84603_Properties_Cmb_JunctionMaterialID.Size = new System.Drawing.Size(137,18);
this.r84603_Properties_Lbl_FrameType.Size = new System.Drawing.Size(100,18);
this.r84603_Properties_Cmb_FrameTypeID.Size = new System.Drawing.Size(143,18);
this.r84603_Properties_Lbl_JunctionType.Size = new System.Drawing.Size(100,18);
this.r84603_Properties_Cmb_JunctionTypeID.Size = new System.Drawing.Size(118,18);
this.r84603_Properties_Lbl_JunctionID.Size = new System.Drawing.Size(75,18);
this.r84603_Properties_Txt_JunctionID.Size = new System.Drawing.Size(68,18);
this.r84603_Properties_Lbl_Enabled.Size = new System.Drawing.Size(56,18);
this.r84603_Properties_Chk_IsEnabled.Size = new System.Drawing.Size(25,18);
this.r84603_Properties_Lbl_CID.Size = new System.Drawing.Size(37,18);
this.r84603_Properties_Txt_CID.Size = new System.Drawing.Size(90,18);
this.r84603_Properties_Lbl_LifeCycleStatus.Size = new System.Drawing.Size(112,18);
this.r84603_Properties_Cmb_LifeCycleStatusID.Size = new System.Drawing.Size(118,18);
this.r84603_Properties_Lbl_CoverDiameter.Size = new System.Drawing.Size(100,18);
this.r84603_Properties_Cmb_CoverDiameterID.Size = new System.Drawing.Size(118,18);
this.r84603_Properties_Lbl_CoverType.Size = new System.Drawing.Size(100,18);
this.r84603_Properties_Cmb_CoverTYpeID.Size = new System.Drawing.Size(156,18);
this.r84603_Properties_Vmg_Properties.Text ="Properties";
this.r84603_Properties_Lbl_SurfaceCover.Text ="Surface Cover:";
this.r84603_Properties_Cmb_SurfaceCoverID.Tag ="SurfaceCoverID";
this.r84603_Properties_Cmb_SurfaceCoverID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_Comment.Text ="Comment:";
this.r84603_Properties_Txtm_Comment.Tag ="Comment";
this.r84603_Properties_Txtm_Comment.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Txtm_Comment.Multiline = true;
this.r84603_Properties_Txtm_Comment.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
this.r84603_Properties_Lbl_AccessType.Text ="Access Type:";
this.r84603_Properties_Cmb_AccessTypeID.Tag ="AccessTypeID";
this.r84603_Properties_Cmb_AccessTypeID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_Depth.Text ="Depth - Flow to Rim:";
this.r84603_Properties_Txt_Depth.Tag ="Depth";
this.r84603_Properties_Txt_Depth.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_EastFlowLine.Text ="East Flow-Line:";
this.r84603_Properties_Txt_EastFlowLine.Tag ="EastFlowLine";
this.r84603_Properties_Txt_EastFlowLine.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_SouthFlowLine.Text ="South Flow-Line:";
this.r84603_Properties_Txt_SouthFlowLine.Tag ="SouthFlowLine";
this.r84603_Properties_Txt_SouthFlowLine.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_NorthFlowLine.Text ="North Flow-Line:";
this.r84603_Properties_Txt_NorthFlowLine.Tag ="NorthFlowLine";
this.r84603_Properties_Txt_NorthFlowLine.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_FlowElevation.Text ="Flow Elevation:";
this.r84603_Properties_Txt_FlowElevation.Tag ="FlowElevation";
this.r84603_Properties_Txt_FlowElevation.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_WestFlowLine.Text ="West Flow-Line:";
this.r84603_Properties_Txt_WestFlowLine.Tag ="WestFlowLine";
this.r84603_Properties_Txt_WestFlowLine.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_Diameter.Text ="Diameter:";
this.r84603_Properties_Txt_Diameter.Tag ="Diameter";
this.r84603_Properties_Txt_Diameter.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_RingMaterial.Text ="Ring Material:";
this.r84603_Properties_Cmb_RingMaterialID.Tag ="RingMaterialID";
this.r84603_Properties_Cmb_RingMaterialID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_JunctionMaterial.Text ="Junction Material:";
this.r84603_Properties_Cmb_JunctionMaterialID.Tag ="JunctionMaterialID";
this.r84603_Properties_Cmb_JunctionMaterialID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_FrameType.Text ="Frame Type:";
this.r84603_Properties_Cmb_FrameTypeID.Tag ="FrameTypeID";
this.r84603_Properties_Cmb_FrameTypeID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_JunctionType.Text ="Junction Type:";
this.r84603_Properties_Cmb_JunctionTypeID.Tag ="JunctionTypeID";
this.r84603_Properties_Cmb_JunctionTypeID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_JunctionID.Text ="Junction ID:";
this.r84603_Properties_Txt_JunctionID.Tag ="FeatureID";
this.r84603_Properties_Txt_JunctionID.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_Enabled.Text ="Enabled:";
this.r84603_Properties_Chk_IsEnabled.Tag ="IsEnabled";
this.r84603_Properties_Chk_IsEnabled.Click += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_CID.Text ="CID:";
this.r84603_Properties_Txt_CID.Tag ="CID";
this.r84603_Properties_Txt_CID.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_LifeCycleStatus.Text ="Life Cycle Status:";
this.r84603_Properties_Cmb_LifeCycleStatusID.Tag ="LifeCycleStatusID";
this.r84603_Properties_Cmb_LifeCycleStatusID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_CoverDiameter.Text ="Cover Diameter:";
this.r84603_Properties_Cmb_CoverDiameterID.Tag ="CoverDiameterID";
this.r84603_Properties_Cmb_CoverDiameterID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Lbl_CoverType.Text ="Cover Type:";
this.r84603_Properties_Cmb_CoverTYpeID.Tag ="CoverTypeID";
this.r84603_Properties_Cmb_CoverTYpeID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84603_Properties_Vmg_Properties.BackColor = System.Drawing.Color.Silver;
this.r84603_Properties_Lbl_SurfaceCover.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_Comment.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_AccessType.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_Depth.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_EastFlowLine.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_SouthFlowLine.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_NorthFlowLine.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_FlowElevation.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_WestFlowLine.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_Diameter.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_RingMaterial.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_JunctionMaterial.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_FrameType.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_JunctionType.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_JunctionID.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_Enabled.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_CID.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_LifeCycleStatus.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_CoverDiameter.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_Lbl_CoverType.ForeColor = System.Drawing.Color.DarkBlue;
this.r84603_Properties_rectangle1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle26.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle27.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle25.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle19.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle23.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle22.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle21.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle20.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle24.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle18.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle17.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle16.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle15.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle14.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle8.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle10.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle9.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle11.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle12.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle13.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84603_Properties_rectangle2.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle26.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle27.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle25.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle19.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle23.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle22.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle21.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle20.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle24.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle18.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle17.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle16.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle15.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle14.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle8.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle10.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle9.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle11.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle12.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_rectangle13.BackColor = System.Drawing.SystemColors.Window;
this.r84603_Properties_Vmg_Properties.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
this.r84603_Properties_Lbl_SurfaceCover.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_Comment.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_AccessType.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_Depth.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_EastFlowLine.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_SouthFlowLine.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_NorthFlowLine.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_FlowElevation.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_WestFlowLine.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_Diameter.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_RingMaterial.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_JunctionMaterial.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_FrameType.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_JunctionType.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_JunctionID.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_Enabled.TextAlign = System.Drawing.ContentAlignment.TopCenter;
this.r84603_Properties_Lbl_CID.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_LifeCycleStatus.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_CoverDiameter.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Lbl_CoverType.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84603_Properties_Txtm_Comment.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
this.r84603_Properties_Txt_Depth.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Properties_Txt_EastFlowLine.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Properties_Txt_SouthFlowLine.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Properties_Txt_NorthFlowLine.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Properties_Txt_FlowElevation.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Properties_Txt_WestFlowLine.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Properties_Txt_Diameter.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
this.r84603_Properties_Txt_JunctionID.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Properties_Txt_CID.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
this.r84603_Properties_Vmg_Properties.Font = new System.Drawing.Font("Arial",12f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_SurfaceCover.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_SurfaceCoverID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_Comment.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txtm_Comment.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_AccessType.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_AccessTypeID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_Depth.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_Depth.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_EastFlowLine.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_EastFlowLine.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_SouthFlowLine.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_SouthFlowLine.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_NorthFlowLine.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_NorthFlowLine.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_FlowElevation.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_FlowElevation.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_WestFlowLine.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_WestFlowLine.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_Diameter.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_Diameter.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_RingMaterial.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_RingMaterialID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_JunctionMaterial.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_JunctionMaterialID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_FrameType.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_FrameTypeID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_JunctionType.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_JunctionTypeID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_JunctionID.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_JunctionID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_Enabled.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Chk_IsEnabled.Font = new System.Drawing.Font("Wingdings",8.5f,System.Drawing.FontStyle.Regular);
this.r84603_Properties_Lbl_CID.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Txt_CID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_LifeCycleStatus.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_LifeCycleStatusID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_CoverDiameter.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_CoverDiameterID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Lbl_CoverType.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Cmb_CoverTYpeID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84603_Properties_Vmg_Properties.Padding  = new System.Windows.Forms.Padding( 2,2,2,2);
this.r84603_Properties_Lbl_SurfaceCover.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_SurfaceCoverID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_Comment.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Txtm_Comment.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_AccessType.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_AccessTypeID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_Depth.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Txt_Depth.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_EastFlowLine.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Txt_EastFlowLine.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_SouthFlowLine.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Txt_SouthFlowLine.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_NorthFlowLine.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Txt_NorthFlowLine.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_FlowElevation.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Txt_FlowElevation.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_WestFlowLine.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Txt_WestFlowLine.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_Diameter.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Txt_Diameter.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_RingMaterial.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_RingMaterialID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_JunctionMaterial.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_JunctionMaterialID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_FrameType.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_FrameTypeID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_JunctionType.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_JunctionTypeID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_JunctionID.Padding  = new System.Windows.Forms.Padding( 2,2,0,2);
this.r84603_Properties_Txt_JunctionID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_Enabled.Padding  = new System.Windows.Forms.Padding( 2,2,0,0);
this.r84603_Properties_Chk_IsEnabled.Padding  = new System.Windows.Forms.Padding( 2,0,2,1);
this.r84603_Properties_Lbl_CID.Padding  = new System.Windows.Forms.Padding( 2,2,2,2);
this.r84603_Properties_Txt_CID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_LifeCycleStatus.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_LifeCycleStatusID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_CoverDiameter.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_CoverDiameterID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_Lbl_CoverType.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84603_Properties_Cmb_CoverTYpeID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84603_Properties_rectangle3.Controls.Add(this.r84603_Properties_Vmg_Properties);
this.r84603_Properties_rectangle1.Controls.Add(this.r84603_Properties_rectangle3);
this.r84603_Properties_rectangle26.Controls.Add(this.r84603_Properties_Lbl_SurfaceCover);
this.r84603_Properties_rectangle26.Controls.Add(this.r84603_Properties_Cmb_SurfaceCoverID);
this.r84603_Properties_rectangle7.Controls.Add(this.r84603_Properties_rectangle26);
this.r84603_Properties_rectangle27.Controls.Add(this.r84603_Properties_Lbl_Comment);
this.r84603_Properties_rectangle27.Controls.Add(this.r84603_Properties_Txtm_Comment);
this.r84603_Properties_rectangle7.Controls.Add(this.r84603_Properties_rectangle27);
this.r84603_Properties_rectangle25.Controls.Add(this.r84603_Properties_Lbl_AccessType);
this.r84603_Properties_rectangle25.Controls.Add(this.r84603_Properties_Cmb_AccessTypeID);
this.r84603_Properties_rectangle7.Controls.Add(this.r84603_Properties_rectangle25);
this.r84603_Properties_rectangle2.Controls.Add(this.r84603_Properties_rectangle7);
this.r84603_Properties_rectangle19.Controls.Add(this.r84603_Properties_Lbl_Depth);
this.r84603_Properties_rectangle19.Controls.Add(this.r84603_Properties_Txt_Depth);
this.r84603_Properties_rectangle6.Controls.Add(this.r84603_Properties_rectangle19);
this.r84603_Properties_rectangle23.Controls.Add(this.r84603_Properties_Lbl_EastFlowLine);
this.r84603_Properties_rectangle23.Controls.Add(this.r84603_Properties_Txt_EastFlowLine);
this.r84603_Properties_rectangle6.Controls.Add(this.r84603_Properties_rectangle23);
this.r84603_Properties_rectangle22.Controls.Add(this.r84603_Properties_Lbl_SouthFlowLine);
this.r84603_Properties_rectangle22.Controls.Add(this.r84603_Properties_Txt_SouthFlowLine);
this.r84603_Properties_rectangle6.Controls.Add(this.r84603_Properties_rectangle22);
this.r84603_Properties_rectangle21.Controls.Add(this.r84603_Properties_Lbl_NorthFlowLine);
this.r84603_Properties_rectangle21.Controls.Add(this.r84603_Properties_Txt_NorthFlowLine);
this.r84603_Properties_rectangle6.Controls.Add(this.r84603_Properties_rectangle21);
this.r84603_Properties_rectangle20.Controls.Add(this.r84603_Properties_Lbl_FlowElevation);
this.r84603_Properties_rectangle20.Controls.Add(this.r84603_Properties_Txt_FlowElevation);
this.r84603_Properties_rectangle6.Controls.Add(this.r84603_Properties_rectangle20);
this.r84603_Properties_rectangle24.Controls.Add(this.r84603_Properties_Lbl_WestFlowLine);
this.r84603_Properties_rectangle24.Controls.Add(this.r84603_Properties_Txt_WestFlowLine);
this.r84603_Properties_rectangle6.Controls.Add(this.r84603_Properties_rectangle24);
this.r84603_Properties_rectangle2.Controls.Add(this.r84603_Properties_rectangle6);
this.r84603_Properties_rectangle18.Controls.Add(this.r84603_Properties_Lbl_Diameter);
this.r84603_Properties_rectangle18.Controls.Add(this.r84603_Properties_Txt_Diameter);
this.r84603_Properties_rectangle5.Controls.Add(this.r84603_Properties_rectangle18);
this.r84603_Properties_rectangle17.Controls.Add(this.r84603_Properties_Lbl_RingMaterial);
this.r84603_Properties_rectangle17.Controls.Add(this.r84603_Properties_Cmb_RingMaterialID);
this.r84603_Properties_rectangle5.Controls.Add(this.r84603_Properties_rectangle17);
this.r84603_Properties_rectangle16.Controls.Add(this.r84603_Properties_Lbl_JunctionMaterial);
this.r84603_Properties_rectangle16.Controls.Add(this.r84603_Properties_Cmb_JunctionMaterialID);
this.r84603_Properties_rectangle5.Controls.Add(this.r84603_Properties_rectangle16);
this.r84603_Properties_rectangle15.Controls.Add(this.r84603_Properties_Lbl_FrameType);
this.r84603_Properties_rectangle15.Controls.Add(this.r84603_Properties_Cmb_FrameTypeID);
this.r84603_Properties_rectangle5.Controls.Add(this.r84603_Properties_rectangle15);
this.r84603_Properties_rectangle14.Controls.Add(this.r84603_Properties_Lbl_JunctionType);
this.r84603_Properties_rectangle14.Controls.Add(this.r84603_Properties_Cmb_JunctionTypeID);
this.r84603_Properties_rectangle5.Controls.Add(this.r84603_Properties_rectangle14);
this.r84603_Properties_rectangle2.Controls.Add(this.r84603_Properties_rectangle5);
this.r84603_Properties_rectangle8.Controls.Add(this.r84603_Properties_Lbl_JunctionID);
this.r84603_Properties_rectangle8.Controls.Add(this.r84603_Properties_Txt_JunctionID);
this.r84603_Properties_rectangle4.Controls.Add(this.r84603_Properties_rectangle8);
this.r84603_Properties_rectangle10.Controls.Add(this.r84603_Properties_Lbl_Enabled);
this.r84603_Properties_rectangle10.Controls.Add(this.r84603_Properties_Chk_IsEnabled);
this.r84603_Properties_rectangle4.Controls.Add(this.r84603_Properties_rectangle10);
this.r84603_Properties_rectangle9.Controls.Add(this.r84603_Properties_Lbl_CID);
this.r84603_Properties_rectangle9.Controls.Add(this.r84603_Properties_Txt_CID);
this.r84603_Properties_rectangle4.Controls.Add(this.r84603_Properties_rectangle9);
this.r84603_Properties_rectangle11.Controls.Add(this.r84603_Properties_Lbl_LifeCycleStatus);
this.r84603_Properties_rectangle11.Controls.Add(this.r84603_Properties_Cmb_LifeCycleStatusID);
this.r84603_Properties_rectangle4.Controls.Add(this.r84603_Properties_rectangle11);
this.r84603_Properties_rectangle12.Controls.Add(this.r84603_Properties_Lbl_CoverDiameter);
this.r84603_Properties_rectangle12.Controls.Add(this.r84603_Properties_Cmb_CoverDiameterID);
this.r84603_Properties_rectangle4.Controls.Add(this.r84603_Properties_rectangle12);
this.r84603_Properties_rectangle13.Controls.Add(this.r84603_Properties_Lbl_CoverType);
this.r84603_Properties_rectangle13.Controls.Add(this.r84603_Properties_Cmb_CoverTYpeID);
this.r84603_Properties_rectangle4.Controls.Add(this.r84603_Properties_rectangle13);
this.r84603_Properties_rectangle2.Controls.Add(this.r84603_Properties_rectangle4);
this.r84603_Properties_rectangle1.Controls.Add(this.r84603_Properties_rectangle2);
this.Controls.Add(this.r84603_Properties_rectangle1);
//this.operationSmartPartWorkSpace = new Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace();
//this.operationSmartPartWorkSpace.Location = new System.Drawing.Point(50,30);
//this.operationSmartPartWorkSpace.Name ="operationSmartPartWorkSpace";
//this.operationSmartPartWorkSpace.Size = new System.Drawing.Size(421, 45);
//this.operationSmartPartWorkSpace.TabIndex = 120;
//this.operationSmartPartWorkSpace.Text ="OperationSmartPart";
//this.Controls.Add(this.operationSmartPartWorkSpace);
this.Resize += new System.EventHandler(this.BaseSmartPart_Resize);
this.Load += new System.EventHandler(this.F846032_Load);
}

TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_CoverTYpeID;
System.Windows.Forms.Label r84603_Properties_Lbl_CoverType;
System.Windows.Forms.Panel r84603_Properties_rectangle13;
TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_CoverDiameterID;
System.Windows.Forms.Label r84603_Properties_Lbl_CoverDiameter;
System.Windows.Forms.Panel r84603_Properties_rectangle12;
TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_LifeCycleStatusID;
System.Windows.Forms.Label r84603_Properties_Lbl_LifeCycleStatus;
System.Windows.Forms.Panel r84603_Properties_rectangle11;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_CID;
System.Windows.Forms.Label r84603_Properties_Lbl_CID;
System.Windows.Forms.Panel r84603_Properties_rectangle9;
TerraScan.UI.Controls.TerraScanCheckBox r84603_Properties_Chk_IsEnabled;
System.Windows.Forms.Label r84603_Properties_Lbl_Enabled;
System.Windows.Forms.Panel r84603_Properties_rectangle10;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_JunctionID;
System.Windows.Forms.Label r84603_Properties_Lbl_JunctionID;
System.Windows.Forms.Panel r84603_Properties_rectangle8;
System.Windows.Forms.Panel r84603_Properties_rectangle4;
TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_JunctionTypeID;
System.Windows.Forms.Label r84603_Properties_Lbl_JunctionType;
System.Windows.Forms.Panel r84603_Properties_rectangle14;
TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_FrameTypeID;
System.Windows.Forms.Label r84603_Properties_Lbl_FrameType;
System.Windows.Forms.Panel r84603_Properties_rectangle15;
TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_JunctionMaterialID;
System.Windows.Forms.Label r84603_Properties_Lbl_JunctionMaterial;
System.Windows.Forms.Panel r84603_Properties_rectangle16;
TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_RingMaterialID;
System.Windows.Forms.Label r84603_Properties_Lbl_RingMaterial;
System.Windows.Forms.Panel r84603_Properties_rectangle17;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_Diameter;
System.Windows.Forms.Label r84603_Properties_Lbl_Diameter;
System.Windows.Forms.Panel r84603_Properties_rectangle18;
System.Windows.Forms.Panel r84603_Properties_rectangle5;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_WestFlowLine;
System.Windows.Forms.Label r84603_Properties_Lbl_WestFlowLine;
System.Windows.Forms.Panel r84603_Properties_rectangle24;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_FlowElevation;
System.Windows.Forms.Label r84603_Properties_Lbl_FlowElevation;
System.Windows.Forms.Panel r84603_Properties_rectangle20;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_NorthFlowLine;
System.Windows.Forms.Label r84603_Properties_Lbl_NorthFlowLine;
System.Windows.Forms.Panel r84603_Properties_rectangle21;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_SouthFlowLine;
System.Windows.Forms.Label r84603_Properties_Lbl_SouthFlowLine;
System.Windows.Forms.Panel r84603_Properties_rectangle22;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_EastFlowLine;
System.Windows.Forms.Label r84603_Properties_Lbl_EastFlowLine;
System.Windows.Forms.Panel r84603_Properties_rectangle23;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txt_Depth;
System.Windows.Forms.Label r84603_Properties_Lbl_Depth;
System.Windows.Forms.Panel r84603_Properties_rectangle19;
System.Windows.Forms.Panel r84603_Properties_rectangle6;
TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_AccessTypeID;
System.Windows.Forms.Label r84603_Properties_Lbl_AccessType;
System.Windows.Forms.Panel r84603_Properties_rectangle25;
TerraScan.UI.Controls.TerraScanTextBox r84603_Properties_Txtm_Comment;
System.Windows.Forms.Label r84603_Properties_Lbl_Comment;
System.Windows.Forms.Panel r84603_Properties_rectangle27;
TerraScan.UI.Controls.TerraScanComboBox r84603_Properties_Cmb_SurfaceCoverID;
System.Windows.Forms.Label r84603_Properties_Lbl_SurfaceCover;
System.Windows.Forms.Panel r84603_Properties_rectangle26;
System.Windows.Forms.Panel r84603_Properties_rectangle7;
System.Windows.Forms.Panel r84603_Properties_rectangle2;
System.Windows.Forms.Label r84603_Properties_Vmg_Properties;
System.Windows.Forms.Panel r84603_Properties_rectangle3;
System.Windows.Forms.Panel r84603_Properties_rectangle1;
private Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace operationSmartPartWorkSpace;
}
}




















