namespace D846012
{
partial class F846012
{
private System.ComponentModel.IContainer components = null;
protected override void Dispose(bool disposing)
{
if (disposing && (components != null))
{
components.Dispose();
}
base.Dispose(disposing);
}
private void InitializeComponent()
{
this.Size = new System.Drawing.Size(756,268);
this.MaximumSize = new System.Drawing.Size(756,268);
this.Text ="RDLTest";
this.r84601_Properties_rectangle7 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_Comment = new System.Windows.Forms.Label();
this.r84601_Properties_Txtm_Comment = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle1 = new System.Windows.Forms.Panel();
this.r84601_Properties_rectangle3 = new System.Windows.Forms.Panel();
this.r84601_Properties_Vmg_Properties = new System.Windows.Forms.Label();
this.r84601_Properties_Vmg_Properties.AccessibleName = "r84601_Properties_Vmg_Properties";
this.r84601_Properties_rectangle2 = new System.Windows.Forms.Panel();
this.r84601_Properties_rectangle6 = new System.Windows.Forms.Panel();
this.r84601_Properties_rectangle21 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_Slope = new System.Windows.Forms.Label();
this.r84601_Properties_Txt_Slope = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle20 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_UpStreamElevation = new System.Windows.Forms.Label();
this.r84601_Properties_Txt_UpStreamElevation = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle19 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_UpStreamDepth = new System.Windows.Forms.Label();
this.r84601_Properties_Txt_UpStreamDepth = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle18 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_DownStreamElevation = new System.Windows.Forms.Label();
this.r84601_Properties_Txt_DownStreamElevation = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle17 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_DownStreamDepth = new System.Windows.Forms.Label();
this.r84601_Properties_Txt_DownStreetDepth = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle5 = new System.Windows.Forms.Panel();
this.r84601_Properties_rectangle16 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_SurfaceCover = new System.Windows.Forms.Label();
this.r84601_Properties_Cmb_SurfaceCoverID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84601_Properties_rectangle15 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_AccessType = new System.Windows.Forms.Label();
this.r84601_Properties_Cmb_AccessTypeID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84601_Properties_rectangle14 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_Length = new System.Windows.Forms.Label();
this.r84601_Properties_Txt_Length = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle13 = new System.Windows.Forms.Panel();
this.r84601_Properties_Cmb_DiameterID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84601_Properties_Lbl_Diameter = new System.Windows.Forms.Label();
this.r84601_Properties_rectangle4 = new System.Windows.Forms.Panel();
this.r84601_Properties_rectangle12 = new System.Windows.Forms.Panel();
this.r84601_Properties_Cmb_MaterialID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84601_Properties_Lbl_Material = new System.Windows.Forms.Label();
this.r84601_Properties_rectangle11 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_LifeCycleStatus = new System.Windows.Forms.Label();
this.r84601_Properties_Cmb_LifeCycleStatusID = new TerraScan.UI.Controls.TerraScanComboBox();
this.r84601_Properties_rectangle10 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_Enabled = new System.Windows.Forms.Label();
this.r84601_Properties_Chk_IsEnabled = new TerraScan.UI.Controls.TerraScanCheckBox();
this.r84601_Properties_rectangle9 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_CID = new System.Windows.Forms.Label();
this.r84601_Properties_Txt_CID = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle8 = new System.Windows.Forms.Panel();
this.r84601_Properties_Lbl_PipeID = new System.Windows.Forms.Label();
this.r84601_Properties_Txt_PipeID = new TerraScan.UI.Controls.TerraScanTextBox();
this.r84601_Properties_rectangle7.Location = new System.Drawing.Point(0,156);
this.r84601_Properties_rectangle1.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_rectangle3.Location = new System.Drawing.Point(706,0);
this.r84601_Properties_rectangle2.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_rectangle6.Location = new System.Drawing.Point(0,104);
this.r84601_Properties_rectangle21.Location = new System.Drawing.Point(598,0);
this.r84601_Properties_rectangle20.Location = new System.Drawing.Point(461,0);
this.r84601_Properties_rectangle19.Location = new System.Drawing.Point(318,0);
this.r84601_Properties_rectangle18.Location = new System.Drawing.Point(150,0);
this.r84601_Properties_rectangle17.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_rectangle5.Location = new System.Drawing.Point(0,52);
this.r84601_Properties_rectangle16.Location = new System.Drawing.Point(537,0);
this.r84601_Properties_rectangle15.Location = new System.Drawing.Point(312,0);
this.r84601_Properties_rectangle14.Location = new System.Drawing.Point(150,0);
this.r84601_Properties_rectangle13.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_rectangle4.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_rectangle12.Location = new System.Drawing.Point(500,0);
this.r84601_Properties_rectangle11.Location = new System.Drawing.Point(325,0);
this.r84601_Properties_rectangle10.Location = new System.Drawing.Point(250,0);
this.r84601_Properties_rectangle9.Location = new System.Drawing.Point(125,0);
this.r84601_Properties_rectangle8.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Lbl_Comment.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txtm_Comment.Location = new System.Drawing.Point(18,27);
this.r84601_Properties_Txtm_Comment.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Vmg_Properties.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Lbl_Slope.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txt_Slope.Location = new System.Drawing.Point(12,26);
this.r84601_Properties_Txt_Slope.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_UpStreamElevation.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txt_UpStreamElevation.Location = new System.Drawing.Point(18,26);
this.r84601_Properties_Txt_UpStreamElevation.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_UpStreamDepth.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txt_UpStreamDepth.Location = new System.Drawing.Point(12,26);
this.r84601_Properties_Txt_UpStreamDepth.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_DownStreamElevation.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txt_DownStreamElevation.Location = new System.Drawing.Point(12,26);
this.r84601_Properties_Txt_DownStreamElevation.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_DownStreamDepth.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txt_DownStreetDepth.Location = new System.Drawing.Point(12,26);
this.r84601_Properties_Txt_DownStreetDepth.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_SurfaceCover.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Cmb_SurfaceCoverID.Location = new System.Drawing.Point(31,26);
this.r84601_Properties_Cmb_SurfaceCoverID.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_AccessType.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Cmb_AccessTypeID.Location = new System.Drawing.Point(12,26);
this.r84601_Properties_Cmb_AccessTypeID.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_Length.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txt_Length.Location = new System.Drawing.Point(37,26);
this.r84601_Properties_Txt_Length.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Cmb_DiameterID.Location = new System.Drawing.Point(25,26);
this.r84601_Properties_Cmb_DiameterID.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_Diameter.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Cmb_MaterialID.Location = new System.Drawing.Point(12,25);
this.r84601_Properties_Cmb_MaterialID.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_Material.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Lbl_LifeCycleStatus.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Cmb_LifeCycleStatusID.Location = new System.Drawing.Point(21,25);
this.r84601_Properties_Cmb_LifeCycleStatusID.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_Enabled.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Chk_IsEnabled.Location = new System.Drawing.Point(28,26);
this.r84601_Properties_Chk_IsEnabled.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_CID.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txt_CID.Location = new System.Drawing.Point(18,26);
this.r84601_Properties_Txt_CID.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_Lbl_PipeID.Location = new System.Drawing.Point(0,0);
this.r84601_Properties_Txt_PipeID.Location = new System.Drawing.Point(18,26);
this.r84601_Properties_Txt_PipeID.BackColor = System.Drawing.Color.White; 
this.r84601_Properties_rectangle7.Size = new System.Drawing.Size(706,105);
this.r84601_Properties_rectangle1.Size = new System.Drawing.Size(750,262);
this.r84601_Properties_rectangle3.Size = new System.Drawing.Size(44,262);
this.r84601_Properties_rectangle2.Size = new System.Drawing.Size(706,262);
this.r84601_Properties_rectangle6.Size = new System.Drawing.Size(706,52);
this.r84601_Properties_rectangle21.Size = new System.Drawing.Size(108,52);
this.r84601_Properties_rectangle20.Size = new System.Drawing.Size(137,52);
this.r84601_Properties_rectangle19.Size = new System.Drawing.Size(143,52);
this.r84601_Properties_rectangle18.Size = new System.Drawing.Size(168,52);
this.r84601_Properties_rectangle17.Size = new System.Drawing.Size(150,52);
this.r84601_Properties_rectangle5.Size = new System.Drawing.Size(706,52);
this.r84601_Properties_rectangle16.Size = new System.Drawing.Size(169,52);
this.r84601_Properties_rectangle15.Size = new System.Drawing.Size(225,52);
this.r84601_Properties_rectangle14.Size = new System.Drawing.Size(162,52);
this.r84601_Properties_rectangle13.Size = new System.Drawing.Size(150,52);
this.r84601_Properties_rectangle4.Size = new System.Drawing.Size(706,52);
this.r84601_Properties_rectangle12.Size = new System.Drawing.Size(206,52);
this.r84601_Properties_rectangle11.Size = new System.Drawing.Size(175,52);
this.r84601_Properties_rectangle10.Size = new System.Drawing.Size(75,52);
this.r84601_Properties_rectangle9.Size = new System.Drawing.Size(125,52);
this.r84601_Properties_rectangle8.Size = new System.Drawing.Size(125,52);
this.r84601_Properties_Lbl_Comment.Size = new System.Drawing.Size(118,18);
this.r84601_Properties_Txtm_Comment.Size = new System.Drawing.Size(681,68);
this.r84601_Properties_Vmg_Properties.Size = new System.Drawing.Size(44,262);
this.r84601_Properties_Lbl_Slope.Size = new System.Drawing.Size(68,18);
this.r84601_Properties_Txt_Slope.Size = new System.Drawing.Size(87,21);
this.r84601_Properties_Lbl_UpStreamElevation.Size = new System.Drawing.Size(125,18);
this.r84601_Properties_Txt_UpStreamElevation.Size = new System.Drawing.Size(112,21);
this.r84601_Properties_Lbl_UpStreamDepth.Size = new System.Drawing.Size(118,18);
this.r84601_Properties_Txt_UpStreamDepth.Size = new System.Drawing.Size(125,21);
this.r84601_Properties_Lbl_DownStreamElevation.Size = new System.Drawing.Size(150,18);
this.r84601_Properties_Txt_DownStreamElevation.Size = new System.Drawing.Size(143,21);
this.r84601_Properties_Lbl_DownStreamDepth.Size = new System.Drawing.Size(125,18);
this.r84601_Properties_Txt_DownStreetDepth.Size = new System.Drawing.Size(125,21);
this.r84601_Properties_Lbl_SurfaceCover.Size = new System.Drawing.Size(112,18);
this.r84601_Properties_Cmb_SurfaceCoverID.Size = new System.Drawing.Size(131,21);
this.r84601_Properties_Lbl_AccessType.Size = new System.Drawing.Size(100,18);
this.r84601_Properties_Cmb_AccessTypeID.Size = new System.Drawing.Size(206,21);
this.r84601_Properties_Lbl_Length.Size = new System.Drawing.Size(100,18);
this.r84601_Properties_Txt_Length.Size = new System.Drawing.Size(118,21);
this.r84601_Properties_Cmb_DiameterID.Size = new System.Drawing.Size(118,21);
this.r84601_Properties_Lbl_Diameter.Size = new System.Drawing.Size(100,18);
this.r84601_Properties_Cmb_MaterialID.Size = new System.Drawing.Size(187,21);
this.r84601_Properties_Lbl_Material.Size = new System.Drawing.Size(62,18);
this.r84601_Properties_Lbl_LifeCycleStatus.Size = new System.Drawing.Size(137,18);
this.r84601_Properties_Cmb_LifeCycleStatusID.Size = new System.Drawing.Size(150,21);
this.r84601_Properties_Lbl_Enabled.Size = new System.Drawing.Size(56,18);
this.r84601_Properties_Chk_IsEnabled.Size = new System.Drawing.Size(34,18);
this.r84601_Properties_Lbl_CID.Size = new System.Drawing.Size(37,18);
this.r84601_Properties_Txt_CID.Size = new System.Drawing.Size(100,21);
this.r84601_Properties_Lbl_PipeID.Size = new System.Drawing.Size(50,18);
this.r84601_Properties_Txt_PipeID.Size = new System.Drawing.Size(100,21);
this.r84601_Properties_Lbl_Comment.Text ="Comment:";
this.r84601_Properties_Txtm_Comment.Tag ="Comment";
this.r84601_Properties_Txtm_Comment.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Txtm_Comment.Multiline = true;
this.r84601_Properties_Txtm_Comment.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
this.r84601_Properties_Vmg_Properties.Text ="Properties";
this.r84601_Properties_Lbl_Slope.Text ="Slope:";
this.r84601_Properties_Txt_Slope.Tag ="Slope";
this.r84601_Properties_Txt_Slope.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_UpStreamElevation.Text ="Up Stream Elevation:";
this.r84601_Properties_Txt_UpStreamElevation.Tag ="UpElevation";
this.r84601_Properties_Txt_UpStreamElevation.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_UpStreamDepth.Text ="Up Stream Depth:";
this.r84601_Properties_Txt_UpStreamDepth.Tag ="UpDepth";
this.r84601_Properties_Txt_UpStreamDepth.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_DownStreamElevation.Text ="Down Stream Elevation:";
this.r84601_Properties_Txt_DownStreamElevation.Tag ="DownElevation";
this.r84601_Properties_Txt_DownStreamElevation.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_DownStreamDepth.Text ="Down Stream Depth:";
this.r84601_Properties_Txt_DownStreetDepth.Tag ="DownDepth";
this.r84601_Properties_Txt_DownStreetDepth.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_SurfaceCover.Text ="Surface Cover:";
this.r84601_Properties_Cmb_SurfaceCoverID.Tag ="SurfaceCoverID";
this.r84601_Properties_Cmb_SurfaceCoverID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_AccessType.Text ="Access Type:";
this.r84601_Properties_Cmb_AccessTypeID.Tag ="AccessTypeID";
this.r84601_Properties_Cmb_AccessTypeID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_Length.Text ="Length:";
this.r84601_Properties_Txt_Length.Tag ="Length";
this.r84601_Properties_Txt_Length.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Cmb_DiameterID.Tag ="DiameterID";
this.r84601_Properties_Cmb_DiameterID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_Diameter.Text ="Diameter:";
this.r84601_Properties_Cmb_MaterialID.Tag ="MaterialID";
this.r84601_Properties_Cmb_MaterialID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_Material.Text ="Material:";
this.r84601_Properties_Lbl_LifeCycleStatus.Text ="Life Cycle Status:";
this.r84601_Properties_Cmb_LifeCycleStatusID.Tag ="LifeCycleStatusID";
this.r84601_Properties_Cmb_LifeCycleStatusID.SelectionChangeCommitted += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_Enabled.Text ="Enabled:";
this.r84601_Properties_Chk_IsEnabled.Tag ="IsEnabled";
this.r84601_Properties_Chk_IsEnabled.Click += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_CID.Text ="CID:";
this.r84601_Properties_Txt_CID.Tag ="CID";
this.r84601_Properties_Txt_CID.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Lbl_PipeID.Text ="Pipe ID:";
this.r84601_Properties_Txt_PipeID.Tag ="FeatureID";
this.r84601_Properties_Txt_PipeID.TextChanged += new System.EventHandler(this.EditEnabledEvent);
this.r84601_Properties_Vmg_Properties.BackColor = System.Drawing.Color.Silver;
this.r84601_Properties_Lbl_Comment.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_Slope.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_UpStreamElevation.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_UpStreamDepth.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_DownStreamElevation.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_DownStreamDepth.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_SurfaceCover.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_AccessType.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_Length.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_Diameter.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_Material.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_LifeCycleStatus.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_Enabled.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_CID.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_Lbl_PipeID.ForeColor = System.Drawing.Color.DarkBlue;
this.r84601_Properties_rectangle1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
this.r84601_Properties_Lbl_Comment.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Vmg_Properties.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
this.r84601_Properties_Lbl_Slope.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_UpStreamElevation.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_UpStreamDepth.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_DownStreamElevation.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_DownStreamDepth.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_SurfaceCover.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_AccessType.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_Length.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_Diameter.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_Material.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_LifeCycleStatus.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_Enabled.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_CID.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Lbl_PipeID.TextAlign = System.Drawing.ContentAlignment.TopLeft;
this.r84601_Properties_Txtm_Comment.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
this.r84601_Properties_Txt_Slope.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
this.r84601_Properties_Txt_UpStreamElevation.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
this.r84601_Properties_Txt_UpStreamDepth.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
this.r84601_Properties_Txt_DownStreamElevation.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
this.r84601_Properties_Txt_DownStreetDepth.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
this.r84601_Properties_Txt_Length.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
this.r84601_Properties_Txt_CID.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
this.r84601_Properties_Txt_PipeID.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
this.r84601_Properties_Lbl_Comment.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txtm_Comment.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Vmg_Properties.Font = new System.Drawing.Font("Arial",12f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_Slope.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txt_Slope.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_UpStreamElevation.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txt_UpStreamElevation.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_UpStreamDepth.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txt_UpStreamDepth.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_DownStreamElevation.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txt_DownStreamElevation.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_DownStreamDepth.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txt_DownStreetDepth.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_SurfaceCover.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Cmb_SurfaceCoverID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_AccessType.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Cmb_AccessTypeID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_Length.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txt_Length.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Cmb_DiameterID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_Diameter.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Cmb_MaterialID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_Material.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_LifeCycleStatus.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Cmb_LifeCycleStatusID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_Enabled.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Chk_IsEnabled.Font = new System.Drawing.Font("Wingdings",8.5f,System.Drawing.FontStyle.Regular);
this.r84601_Properties_Lbl_CID.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txt_CID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_PipeID.Font = new System.Drawing.Font("Arial",8f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Txt_PipeID.Font = new System.Drawing.Font("Arial",8.5f,System.Drawing.FontStyle.Bold);
this.r84601_Properties_Lbl_Comment.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Txtm_Comment.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Vmg_Properties.Padding  = new System.Windows.Forms.Padding( 2,2,2,2);
this.r84601_Properties_Lbl_Slope.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Txt_Slope.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_UpStreamElevation.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Txt_UpStreamElevation.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_UpStreamDepth.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Txt_UpStreamDepth.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_DownStreamElevation.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Txt_DownStreamElevation.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_DownStreamDepth.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Txt_DownStreetDepth.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_SurfaceCover.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Cmb_SurfaceCoverID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_AccessType.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Cmb_AccessTypeID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_Length.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Txt_Length.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Cmb_DiameterID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_Diameter.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Cmb_MaterialID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_Material.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Lbl_LifeCycleStatus.Padding  = new System.Windows.Forms.Padding( 2,2,2,0);
this.r84601_Properties_Cmb_LifeCycleStatusID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_Enabled.Padding  = new System.Windows.Forms.Padding( 2,2,0,0);
this.r84601_Properties_Chk_IsEnabled.Padding  = new System.Windows.Forms.Padding( 2,0,2,1);
this.r84601_Properties_Lbl_CID.Padding  = new System.Windows.Forms.Padding( 2,2,2,2);
this.r84601_Properties_Txt_CID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_Lbl_PipeID.Padding  = new System.Windows.Forms.Padding( 2,2,0,2);
this.r84601_Properties_Txt_PipeID.Padding  = new System.Windows.Forms.Padding( 2,0,4,1);
this.r84601_Properties_rectangle7.Controls.Add(this.r84601_Properties_Lbl_Comment);
this.r84601_Properties_rectangle7.Controls.Add(this.r84601_Properties_Txtm_Comment);
this.Controls.Add(this.r84601_Properties_rectangle7);
this.r84601_Properties_rectangle3.Controls.Add(this.r84601_Properties_Vmg_Properties);
this.r84601_Properties_rectangle1.Controls.Add(this.r84601_Properties_rectangle3);
this.r84601_Properties_rectangle21.Controls.Add(this.r84601_Properties_Lbl_Slope);
this.r84601_Properties_rectangle21.Controls.Add(this.r84601_Properties_Txt_Slope);
this.r84601_Properties_rectangle6.Controls.Add(this.r84601_Properties_rectangle21);
this.r84601_Properties_rectangle20.Controls.Add(this.r84601_Properties_Lbl_UpStreamElevation);
this.r84601_Properties_rectangle20.Controls.Add(this.r84601_Properties_Txt_UpStreamElevation);
this.r84601_Properties_rectangle6.Controls.Add(this.r84601_Properties_rectangle20);
this.r84601_Properties_rectangle19.Controls.Add(this.r84601_Properties_Lbl_UpStreamDepth);
this.r84601_Properties_rectangle19.Controls.Add(this.r84601_Properties_Txt_UpStreamDepth);
this.r84601_Properties_rectangle6.Controls.Add(this.r84601_Properties_rectangle19);
this.r84601_Properties_rectangle18.Controls.Add(this.r84601_Properties_Lbl_DownStreamElevation);
this.r84601_Properties_rectangle18.Controls.Add(this.r84601_Properties_Txt_DownStreamElevation);
this.r84601_Properties_rectangle6.Controls.Add(this.r84601_Properties_rectangle18);
this.r84601_Properties_rectangle17.Controls.Add(this.r84601_Properties_Lbl_DownStreamDepth);
this.r84601_Properties_rectangle17.Controls.Add(this.r84601_Properties_Txt_DownStreetDepth);
this.r84601_Properties_rectangle6.Controls.Add(this.r84601_Properties_rectangle17);
this.r84601_Properties_rectangle2.Controls.Add(this.r84601_Properties_rectangle6);
this.r84601_Properties_rectangle16.Controls.Add(this.r84601_Properties_Lbl_SurfaceCover);
this.r84601_Properties_rectangle16.Controls.Add(this.r84601_Properties_Cmb_SurfaceCoverID);
this.r84601_Properties_rectangle5.Controls.Add(this.r84601_Properties_rectangle16);
this.r84601_Properties_rectangle15.Controls.Add(this.r84601_Properties_Lbl_AccessType);
this.r84601_Properties_rectangle15.Controls.Add(this.r84601_Properties_Cmb_AccessTypeID);
this.r84601_Properties_rectangle5.Controls.Add(this.r84601_Properties_rectangle15);
this.r84601_Properties_rectangle14.Controls.Add(this.r84601_Properties_Lbl_Length);
this.r84601_Properties_rectangle14.Controls.Add(this.r84601_Properties_Txt_Length);
this.r84601_Properties_rectangle5.Controls.Add(this.r84601_Properties_rectangle14);
this.r84601_Properties_rectangle13.Controls.Add(this.r84601_Properties_Cmb_DiameterID);
this.r84601_Properties_rectangle13.Controls.Add(this.r84601_Properties_Lbl_Diameter);
this.r84601_Properties_rectangle5.Controls.Add(this.r84601_Properties_rectangle13);
this.r84601_Properties_rectangle2.Controls.Add(this.r84601_Properties_rectangle5);
this.r84601_Properties_rectangle12.Controls.Add(this.r84601_Properties_Cmb_MaterialID);
this.r84601_Properties_rectangle12.Controls.Add(this.r84601_Properties_Lbl_Material);
this.r84601_Properties_rectangle4.Controls.Add(this.r84601_Properties_rectangle12);
this.r84601_Properties_rectangle11.Controls.Add(this.r84601_Properties_Lbl_LifeCycleStatus);
this.r84601_Properties_rectangle11.Controls.Add(this.r84601_Properties_Cmb_LifeCycleStatusID);
this.r84601_Properties_rectangle4.Controls.Add(this.r84601_Properties_rectangle11);
this.r84601_Properties_rectangle10.Controls.Add(this.r84601_Properties_Lbl_Enabled);
this.r84601_Properties_rectangle10.Controls.Add(this.r84601_Properties_Chk_IsEnabled);
this.r84601_Properties_rectangle4.Controls.Add(this.r84601_Properties_rectangle10);
this.r84601_Properties_rectangle9.Controls.Add(this.r84601_Properties_Lbl_CID);
this.r84601_Properties_rectangle9.Controls.Add(this.r84601_Properties_Txt_CID);
this.r84601_Properties_rectangle4.Controls.Add(this.r84601_Properties_rectangle9);
this.r84601_Properties_rectangle8.Controls.Add(this.r84601_Properties_Lbl_PipeID);
this.r84601_Properties_rectangle8.Controls.Add(this.r84601_Properties_Txt_PipeID);
this.r84601_Properties_rectangle4.Controls.Add(this.r84601_Properties_rectangle8);
this.r84601_Properties_rectangle2.Controls.Add(this.r84601_Properties_rectangle4);
this.r84601_Properties_rectangle1.Controls.Add(this.r84601_Properties_rectangle2);
this.Controls.Add(this.r84601_Properties_rectangle1);
//this.operationSmartPartWorkSpace = new Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace();
//this.operationSmartPartWorkSpace.Location = new System.Drawing.Point(50,30);
//this.operationSmartPartWorkSpace.Name ="operationSmartPartWorkSpace";
//this.operationSmartPartWorkSpace.Size = new System.Drawing.Size(421, 45);
//this.operationSmartPartWorkSpace.TabIndex = 120;
//this.operationSmartPartWorkSpace.Text ="OperationSmartPart";
//this.Controls.Add(this.operationSmartPartWorkSpace);
this.Resize += new System.EventHandler(this.BaseSmartPart_Resize);
this.Load += new System.EventHandler(this.F846012_Load);
}

TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txt_PipeID;
System.Windows.Forms.Label r84601_Properties_Lbl_PipeID;
System.Windows.Forms.Panel r84601_Properties_rectangle8;
TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txt_CID;
System.Windows.Forms.Label r84601_Properties_Lbl_CID;
System.Windows.Forms.Panel r84601_Properties_rectangle9;
TerraScan.UI.Controls.TerraScanCheckBox r84601_Properties_Chk_IsEnabled;
System.Windows.Forms.Label r84601_Properties_Lbl_Enabled;
System.Windows.Forms.Panel r84601_Properties_rectangle10;
TerraScan.UI.Controls.TerraScanComboBox r84601_Properties_Cmb_LifeCycleStatusID;
System.Windows.Forms.Label r84601_Properties_Lbl_LifeCycleStatus;
System.Windows.Forms.Panel r84601_Properties_rectangle11;
System.Windows.Forms.Label r84601_Properties_Lbl_Material;
TerraScan.UI.Controls.TerraScanComboBox r84601_Properties_Cmb_MaterialID;
System.Windows.Forms.Panel r84601_Properties_rectangle12;
System.Windows.Forms.Panel r84601_Properties_rectangle4;
System.Windows.Forms.Label r84601_Properties_Lbl_Diameter;
TerraScan.UI.Controls.TerraScanComboBox r84601_Properties_Cmb_DiameterID;
System.Windows.Forms.Panel r84601_Properties_rectangle13;
TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txt_Length;
System.Windows.Forms.Label r84601_Properties_Lbl_Length;
System.Windows.Forms.Panel r84601_Properties_rectangle14;
TerraScan.UI.Controls.TerraScanComboBox r84601_Properties_Cmb_AccessTypeID;
System.Windows.Forms.Label r84601_Properties_Lbl_AccessType;
System.Windows.Forms.Panel r84601_Properties_rectangle15;
TerraScan.UI.Controls.TerraScanComboBox r84601_Properties_Cmb_SurfaceCoverID;
System.Windows.Forms.Label r84601_Properties_Lbl_SurfaceCover;
System.Windows.Forms.Panel r84601_Properties_rectangle16;
System.Windows.Forms.Panel r84601_Properties_rectangle5;
TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txt_DownStreetDepth;
System.Windows.Forms.Label r84601_Properties_Lbl_DownStreamDepth;
System.Windows.Forms.Panel r84601_Properties_rectangle17;
TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txt_DownStreamElevation;
System.Windows.Forms.Label r84601_Properties_Lbl_DownStreamElevation;
System.Windows.Forms.Panel r84601_Properties_rectangle18;
TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txt_UpStreamDepth;
System.Windows.Forms.Label r84601_Properties_Lbl_UpStreamDepth;
System.Windows.Forms.Panel r84601_Properties_rectangle19;
TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txt_UpStreamElevation;
System.Windows.Forms.Label r84601_Properties_Lbl_UpStreamElevation;
System.Windows.Forms.Panel r84601_Properties_rectangle20;
TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txt_Slope;
System.Windows.Forms.Label r84601_Properties_Lbl_Slope;
System.Windows.Forms.Panel r84601_Properties_rectangle21;
System.Windows.Forms.Panel r84601_Properties_rectangle6;
System.Windows.Forms.Panel r84601_Properties_rectangle2;
System.Windows.Forms.Label r84601_Properties_Vmg_Properties;
System.Windows.Forms.Panel r84601_Properties_rectangle3;
System.Windows.Forms.Panel r84601_Properties_rectangle1;
TerraScan.UI.Controls.TerraScanTextBox r84601_Properties_Txtm_Comment;
System.Windows.Forms.Label r84601_Properties_Lbl_Comment;
System.Windows.Forms.Panel r84601_Properties_rectangle7;
private Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace operationSmartPartWorkSpace;
}
}















